---
- name: Install MySQL, Nginx, PHP-FPM, Apache2, Mailcatcher
  hosts: default
  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - apache
    - mailcatcher
    - composer
  tasks:
    - name: Set shell for vagrant user
      user: name=vagrant shell=/bin/bash
