---
- name: Commmon | MailUtils
  apt: pkg=mailutils state=latest

- name: MailCatcher | Install MailCatcher
  action: command gem install mailcatcher creates=/usr/bin/mailcatcher

- name: MailCatcher | Configure PHP cli mmailcatcher
  command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php5/cli/php.ini

- name: MailCatcher | Configure PHP scripts mailcatcher
  command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php5/fpm/php.ini

- name: MailCatcher | Kill MailCatcher
  command: pkill mailcatcher
  ignore_errors: yes

- name: MailCatcher | Run MailCatcher
  command: mailcatcher --ip=0.0.0.0
