---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb

- name: innodb config file
  copy: src=innodb.cnf dest=/etc/mysql/conf.d/innodb.cnf owner=root group=root mode=644
  notify: restart mysql

- name: innodb config file
  copy: src=binding.cnf dest=/etc/mysql/conf.d/binding.cnf owner=root group=root mode=644
  notify: restart mysql

- name: infile config file
  copy: src=infile.cnf dest=/etc/mysql/conf.d/infile.cnf owner=root group=root mode=644
  notify: restart mysql

- name: mysql service
  service: name=mysql state=started enabled=yes

- name: create mysql database
  mysql_db: name={{ mysql_db_name }} state=present collation=utf8_general_ci encoding=utf8

- name: mysql permissions (local)
  mysql_user: name={{ mysql_db_user }} host=localhost password={{ mysql_db_password }} priv={{ mysql_db_name }}.*:ALL state=present
- name: mysql permissions (remote)
  mysql_user: name={{ mysql_db_user }} host='%' password={{ mysql_db_password }} priv={{ mysql_db_name }}.*:ALL state=present
